"""added lng and lat to cities

Revision ID: 95540a08420e
Revises: 407cdf442bfe
Create Date: 2025-08-28 16:17:05.658413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95540a08420e'
down_revision: Union[str, Sequence[str], None] = '407cdf442bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('cities', sa.Column('lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'lng')
    op.drop_column('cities', 'lat')
    # ### end Alembic commands ###
